[package]
name = "ebql-client"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
ebql = { path = "../ebql" }
env_logger = "0.11.3"
log = "0.4.21"
nom-sql = { git = "https://github.com/ringtack/nom-sql.git", branch = "master" }
